//3D
#include "res://addons/sdf_visual_shader_nodes/3D/box.gdshaderinc"
#include "res://addons/sdf_visual_shader_nodes/3D/box_frame.gdshaderinc"
#include "res://addons/sdf_visual_shader_nodes/3D/capped_cone.gdshaderinc"
#include "res://addons/sdf_visual_shader_nodes/3D/capped_torus.gdshaderinc"
#include "res://addons/sdf_visual_shader_nodes/3D/cone.gdshaderinc"
#include "res://addons/sdf_visual_shader_nodes/3D/cylinder.gdshaderinc"
#include "res://addons/sdf_visual_shader_nodes/3D/inf_cylinder.gdshaderinc"
#include "res://addons/sdf_visual_shader_nodes/3D/link.gdshaderinc"
#include "res://addons/sdf_visual_shader_nodes/3D/round_box.gdshaderinc"
#include "res://addons/sdf_visual_shader_nodes/3D/sphere.gdshaderinc"
#include "res://addons/sdf_visual_shader_nodes/3D/torus.gdshaderinc"

//2D
#include "res://addons/sdf_visual_shader_nodes/2D/rect.gdshaderinc"
#include "res://addons/sdf_visual_shader_nodes/2D/circle.gdshaderinc"

//operations
#include "res://addons/sdf_visual_shader_nodes/operations/extrude.gdshaderinc"